using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IsItFurvesterAlready.TelegramBot
{
    public static class Functions
    {
        // Check the dates for Furvester and generate fitting reply
        public static string YesOrNo(Config appConfig)
        {
            var currentDate = DateTime.Today;
            var startDate = appConfig?.Dates?.StartDate;
            var endDate = appConfig?.Dates?.EndDate;
            int daysUntil = (startDate - currentDate).Value.Days;

            if (currentDate > endDate)
            {
                return "No. But... wait. I don't think I have the right dates anymore. Please contact @Tecraaa";
            }

            if (currentDate >= startDate)
            {
                return "Yes! Enjoy it while it lasts.";
            }

            if (daysUntil == 1)
            {
                return "No. But Furvester will start tomorrow!";
            }

            return $"No. But Furvester will start in {daysUntil} days!";
        }

        // Check whether the message can be sent based on the last sent DateTime
        // This was generated by ChatGPT. My brain lagged.
        public static bool CanSendMessage(Dictionary<long, DateTime> dictionary, long chatId, int timeOutSeconds)
        {
            if (dictionary.TryGetValue(chatId, out DateTime lastSentTime))
            {
                // Calculate the time difference
                TimeSpan timeDifference = DateTime.UtcNow - lastSentTime;
                // Check if the difference is more than thottleTimeOutSeconds seconds
                return timeDifference.TotalSeconds > timeOutSeconds;
            }

            // If there's no record of the chat ID, allow the message to be sent
            return true;
        }
    }
}
